---
catalog-name: cdl_tp_prod
schema-name: gold_tp
rls-schema-name: gold_tp
tenant-id: '{{secrets/KeyVault_Scope/pg-azure-tenant-id}}' #P&G Azure Tenant
cdl-metadata:
  # metadata-api config
  api-url: https://api.pgcloud.com/othersupportingdata/it/v1/metadata
  #todo: replace with the proper azure key-vault and secret name
  api-app-id: '{{secrets/KeyVault_Scope/metadata-api-app-id}}'
  sp-app-id: '{{secrets/KeyVault_Scope/az-sp-cdl-flexflow-tp-01-prod-ID}}'
  sp-secret: '{{secrets/KeyVault_Scope/az-sp-cdl-flexflow-tp-01-prod-KEY}}'
  # integration-service configs
  integration-api-url: https://func-uicaintsvc-p101.azurewebsites.net
  #todo: replace with the proper azure key-vault and secret name
  integration-api-app-id: '{{secrets/KeyVault_Scope/az-sp-cdl-flexflow-tp-01-prod-ID}}'
  # publisher configs
  logical-layer-app-name: "Core Data Lake - Trade Panel"
  data-layer-app-name: "Trade Panel FlexFlow Light Refined"
  data-provider-code: "TP"

storage:
  account-name: "sa01flexflowtp01prod"
  container-name: "tp-publish-data"
  # This credential is only necassary if you need to use a different credential for accessing storage
  sp-app-id: '{{secrets/KeyVault_Scope/az-sp-cdl-flexflow-tp-01-prod-ID}}'
  sp-secret: '{{secrets/KeyVault_Scope/az-sp-cdl-flexflow-tp-01-prod-KEY}}'
tables:
- logical-name: "TP_PROD_DIM"
  destination-path: "TP_PROD_DIM"
  unity-catalog-table-name: "TP_PROD_DIM"
  data-signal-keys: [6888]  # it can be either key or string
  data-type-code: "TP"
  part-definition: "part_srce_sys_id/part_cntrt_id"
  secure-group-key: 0
