steps:
  - task: AzureKeyVault@2
    displayName: "Task - Getting secrets from Azure KeyVault"
    inputs:
      azureSubscription: $(azure_subscription)
      KeyVaultName: $(keyvault_name)
      RunAsPreJob: true
